/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alumnes.Modulos.GestioAlumnes.GestioAO.Vista;


/**
 *
 * @author carlos
 */
public class ModificarAlumneOnline extends javax.swing.JFrame {

    /**
     * Creates new form AfegirAlumneOnline
     */
    public ModificarAlumneOnline() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cognom = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        especialitat = new javax.swing.JTextField();
        curs = new javax.swing.JTextField();
        DNI = new javax.swing.JTextField();
        direccio = new javax.swing.JTextField();
        nomNo = new javax.swing.JLabel();
        cognomNo = new javax.swing.JLabel();
        DNINo = new javax.swing.JLabel();
        especialitatNo = new javax.swing.JLabel();
        direccioNo = new javax.swing.JLabel();
        cursNo = new javax.swing.JLabel();
        naixementNo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        naixement = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        becaNo = new javax.swing.JLabel();
        desconexioNo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        conexio = new javax.swing.JTextField();
        beca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        desconexio = new javax.swing.JTextField();
        conexioNo = new javax.swing.JLabel();
        passNo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        userNo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        tornar = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Alumne Online"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dades Basiques"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(cognom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 101, -1));
        jPanel4.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 101, -1));
        jPanel4.add(especialitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 101, -1));
        jPanel4.add(curs, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 101, -1));

        DNI.setEditable(false);
        jPanel4.add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 101, -1));
        jPanel4.add(direccio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 101, -1));

        nomNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel4.add(nomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        cognomNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel4.add(cognomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        DNINo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel4.add(DNINo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        especialitatNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel4.add(especialitatNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        direccioNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel4.add(direccioNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        cursNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel4.add(cursNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        naixementNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel4.add(naixementNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel1.setText("Nom:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("Cognom:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("DNI:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setText("Especialitat:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setText("Direccio:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel6.setText("Curs:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel7.setText("Data Naixement:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        naixement.setDateFormatString("dd/MM/yyyy");
        naixement.setFocusCycleRoot(true);
        naixement.setMaxSelectableDate(new java.util.Date(253370764867000L));
        jPanel4.add(naixement, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 27, 270, 237));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 300, 280));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dades Avançades"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        becaNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel5.add(becaNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        desconexioNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel5.add(desconexioNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel10.setText("User:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel5.add(conexio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 101, -1));
        jPanel5.add(beca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 101, -1));

        jLabel11.setText("Pass:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel5.add(desconexio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 101, -1));

        conexioNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel5.add(conexioNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        passNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel5.add(passNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel9.setText("Hora de Desconexio:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel5.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 101, -1));

        userNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnes/Img/no.png"))); // NOI18N
        jPanel5.add(userNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel12.setText("Beca:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel5.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 101, -1));

        jLabel8.setText("Hora de Conexio:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 27, 290, 180));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 320, 230));

        guardar.setText("Guardar");
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        tornar.setText("Tornar");
        jPanel1.add(tornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        resultado.setEditable(false);
        resultado.setFocusable(false);
        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 310, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 670, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField DNI;
    public static javax.swing.JLabel DNINo;
    public static javax.swing.JTextField beca;
    public static javax.swing.JLabel becaNo;
    public static javax.swing.JTextField cognom;
    public static javax.swing.JLabel cognomNo;
    public static javax.swing.JTextField conexio;
    public static javax.swing.JLabel conexioNo;
    public static javax.swing.JTextField curs;
    public static javax.swing.JLabel cursNo;
    public static javax.swing.JTextField desconexio;
    public static javax.swing.JLabel desconexioNo;
    public static javax.swing.JTextField direccio;
    public static javax.swing.JLabel direccioNo;
    public static javax.swing.JTextField especialitat;
    public static javax.swing.JLabel especialitatNo;
    public static javax.swing.JButton guardar;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public static com.toedter.calendar.JDateChooser naixement;
    public static javax.swing.JLabel naixementNo;
    public static javax.swing.JTextField nom;
    public static javax.swing.JLabel nomNo;
    public static javax.swing.JTextField pass;
    public static javax.swing.JLabel passNo;
    public static javax.swing.JTextField resultado;
    public static javax.swing.JButton tornar;
    public static javax.swing.JTextField user;
    public static javax.swing.JLabel userNo;
    // End of variables declaration//GEN-END:variables
}
