/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alumnes.Modulos.Login.Vista;

/**
 *
 * @author Stricker333
 */
public class VentanaRecordar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRecordar
     */
    public VentanaRecordar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        error1 = new javax.swing.JLabel();
        InvalidUserLabel = new javax.swing.JLabel();
        InvalidPass1Label = new javax.swing.JLabel();
        InvalidPass2Label = new javax.swing.JLabel();
        InvalidMailLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        Recuperar = new javax.swing.JButton();
        token = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 127, -1, 13));
        jPanel3.add(InvalidUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 16, 25, 25));
        jPanel3.add(InvalidPass1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 96, 25, 25));
        jPanel3.add(InvalidPass2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 178, 25, 25));
        jPanel3.add(InvalidMailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 197, 25, 25));

        jLabel2.setText("Usuario:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 46, -1, -1));

        jLabel3.setText("Token:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 170, -1, -1));
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 165, -1));

        Recuperar.setText("Recuperar");
        jPanel3.add(Recuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        token.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokenActionPerformed(evt);
            }
        });
        jPanel3.add(token, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 260, -1));

        jLabel1.setText("Nueva");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        jPanel3.add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 165, -1));

        jLabel4.setText("Contraseña:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, 266));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tokenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRecordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRecordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRecordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRecordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRecordar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel InvalidMailLabel;
    public static javax.swing.JLabel InvalidPass1Label;
    public static javax.swing.JLabel InvalidPass2Label;
    public static javax.swing.JLabel InvalidUserLabel;
    public static javax.swing.JButton Recuperar;
    public static javax.swing.JLabel error1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JPasswordField newPass;
    public static javax.swing.JTextField token;
    public static javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
